const memeData = {
  success: true,
  data: {
    memes: [
      {
        id: "61579",
        name: "One Does Not Simply",
        url: "https://i.imgflip.com/1bij.jpg",
        width: 568,
        height: 335,
        box_count: 2,
      },
      {
        id: "101470",
        name: "Ancient Aliens",
        url: "https://i.imgflip.com/26am.jpg",
        width: 500,
        height: 437,
        box_count: 2,
      },
      {
        id: "252600902",
        name: "Distracted Boyfriend",
        url: "https://i.imgflip.com/1ur9b0.jpg",
        width: 1200,
        height: 800,
        box_count: 3,
      },
      {
        id: "61532",
        name: "X, X Everywhere",
        url: "https://i.imgflip.com/1bhm.jpg",
        width: 500,
        height: 500,
        box_count: 2,
      },
      {
        id: "14371066",
        name: "Sparta Leonidas",
        url: "https://i.imgflip.com/9vm4.jpg",
        width: 620,
        height: 465,
        box_count: 2,
      },
      {
        id: "61581",
        name: "The Most Interesting Man in the World",
        url: "https://i.imgflip.com/1bhk.jpg",
        width: 500,
        height: 333,
        box_count: 2,
      },
      {
        id: "124822590",
        name: "Mocking SpongeBob",
        url: "https://i.imgflip.com/1otk96.jpg",
        width: 502,
        height: 353,
        box_count: 2,
      },
      {
        id: "101288",
        name: "Doge",
        url: "https://i.imgflip.com/4t0m5.jpg",
        width: 584,
        height: 529,
        box_count: 2,
      },
      {
        id: "61520",
        name: "Batman Slapping Robin",
        url: "https://i.imgflip.com/1bhf.jpg",
        width: 400,
        height: 387,
        box_count: 2,
      },
      {
        id: "1035805",
        name: "Is This A Pigeon",
        url: "https://i.imgflip.com/28s2.jpg",
        width: 898,
        height: 701,
        box_count: 2,
      },
    ],
  },
};

export default memeData;
